ecc_master_path: /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
output_path: /home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/02.circlemap_3
input_file:
    MB_5:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.QC/trim/SRR19454704_1_val_1.fq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.QC/trim//SRR19454704_2_val_2.fq.gz"]
    MB_6:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.QC/trim/SRR19454705_1_val_1.fq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.QC/trim//SRR19454705_2_val_2.fq.gz"]
    MB_7:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.QC/trim/SRR19454706_1_val_1.fq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.QC/trim//SRR19454706_2_val_2.fq.gz"]

threads: 12
reference: hg38
user_ref: None