ecc_master_path: /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
output_path: /home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data//01.QC
input_file:
    MB_normal_1:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454698_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454698_2.fastq.gz"]
    MB_normal_2:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454699_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454699_2.fastq.gz"]
    MB_1:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454700_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454700_2.fastq.gz"]
    MB_2:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454701_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454701_2.fastq.gz"]
    MB_3:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454702_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454702_2.fastq.gz"]
    MB_4:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454703_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454703_2.fastq.gz"]
    MB_5:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454704_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454704_2.fastq.gz"]
    MB_6:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454705_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454705_2.fastq.gz"]
    MB_7:
            ["/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454706_1.fastq.gz","/home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/01.download_data/SRR19454706_2.fastq.gz"]
threads: 2
paired: True
