ecc_master_path: /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
output_path: ./example/result/01.QC
input_file:
    test_data:
            ["./example/circlemap/test_data_1.fastq.gz","./example/circlemap/test_data_2.fastq.gz"]
    test_data_copy:
            ["./example/circlemap/test_data_copy_1.fastq.gz","./example/circlemap/test_data_copy_2.fastq.gz"]
    GBM20:
            ["./example/AA/GBM20_1.fq.gz","./example/AA/GBM20_2.fq.gz"]
    GBM20_copy:
            ["./example/AA/GBM20_copy_1.fq.gz","./example/AA/GBM20_copy_2.fq.gz"]
threads: 4
paired: True
